### ISSUE TITLE
consider using only project name in namespace 

### ISSUE THREAD

**Issue by alidlorenzo** [applied-science/js-interop#20]
is there a reason you chose to use organization-name/project-name in namespace, rather than just project name itself? i.e. keep full name for the deps reuire, but only project name for the namespace require

this library is imported a lot, so it'd be great to be able to write `[js-interop :as j]` rather than `[applied-science.js-interop :as j]`.

**Comment by mhuebert** [comment]
Thanks for the comment. Single-segment namespaces are [generally discouraged](https://stackoverflow.com/questions/13567078/whats-wrong-with-single-segment-namespaces), and namespaces can suffer from the same collision problems as maven/clojars coordinates (ie. problems arise if you bring in multiple deps that contain overlapping namespaces), so we opt for the safer approach of using a fully qualified name for both the dep & namespace. Personally I rely on my editor's autocomplete/autosuggest to ease the burden.

**Comment by alidlorenzo** [comment]
ok, understandable. 

but i'll add that cljs-bean, project in similar spirit and by maintainer of cljs, uses only project name in its namespace 

there's lot of projects that do both approaches, so not sure if it's totally discourage anymore, but doesn't seem like it is.

**Comment by mhuebert** [comment]
cljs-bean does not use single-segment namespaces - https://github.com/mfikes/cljs-bean/blob/master/src/cljs_bean/core.cljs#L1

we could of course have chosen `js-interop.core`, and `core` is shorter (4 characters), but does not add any meaning/differentiation.

**Comment by alidlorenzo** [comment]
oh I did not mean single segment namespace, just that, for example, `[cljs-bean.core :as bean]` is a lot more pleasant to read and easier to remember, than say `[mfikes/cljs-bean :as bean]` 

but yeah this is definitely a personal preference, it's your choice if you prefer including the organization name in the ns
