### ISSUE TITLE
Error getting length of a string

### ISSUE THREAD

**Issue by den1k** [applied-science/js-interop#22]
Works on arrays:

```clojure
(.-length #js [])
=> 0
(j/get #js [] :length)
=> 0
```

Fails on strings:
```clojure
(.-length "1")
; => 1

(j/get "1" :length)
; => #object[TypeError TypeError: Cannot use 'in' operator to search for 'length' in 1]
```

**Comment by mhuebert** [comment]
Hey @den1k, thanks for the report. Fixed this in 0.3.1. Tests: https://github.com/applied-science/js-interop/blob/master/src/test/applied_science/js_interop_test.cljs#L55

I was doing an `in` check on the object which failed on strings. I've changed the lookup logic to first check for `nil?` on the object, then get the result and see if it is `undefined?` to decide whether we return the "not-found" value. This may even speed up 2-arity `j/get` calls (ever so slightly).
